[project]
name = "edge-rag"
version = "0.1.1"
description = "Research Project for KES2026"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "lancedb>=0.29.2",
    "lxml>=6.0.2",
    "matplotlib>=3.10.8",
    "ollama>=0.6.1",
    "openai>=1.0.0",
    "python-dotenv>=1.0.0",
    "google-generativeai>=0.8.6",
    "pandas>=3.0.0",
    "pyarrow>=23.0.0",
    "python-evtx>=0.8.1",
    "requests>=2.32.5",
    "seaborn>=0.13.2",
    "sentence-transformers>=5.2.2",
    "tqdm>=4.67.3",
]

[dependency-groups]
dev = [
    "ruff>=0.15.1",
]
